name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make deps

    - name: Run Test
      run: make test
      
    - name: Test Coverage
      run: make cover
      
    - name: Build Project
      run: make build
